
#rule subtract background
do_inverse : True

#rule coil_unet
coil_unet_weights : "/lisc/scratch/neurobiology/zimmer/jalaja/behaviour/codes/unet-master/training_result/2474992_10_w_validation_2batchsize_500steps_100epochs_10patience/unet_master.hdf5"

unet_segmentation_model : "/lisc/scratch/neurobiology/zimmer/jalaja/behaviour/codes/Pytorch-UNet/checkpoints/checkpoint_epoch5.pth"
filter_prediction: 1
max_contour_size: 240000
fill_in: 1

#rule binarize_coil
coil_threshold : 220
coil_new_value : 255

#blur_gaussian: 49 #needs to be odd
#blur : 1 #needs to be odd

min_contour_size : 80000
#tolerance : 0.5
inner_contour_to_fill : 2000.0

#rule erode_binary_mask:
iterations : 3

# rule tiff2avi:
fourcc : 0
fps : 10
downsample_for_DLC : 1  #downdownsample_for_DLC 1 = yes 0 = no -> will downsample video to 512 for DLC to track head and tail properly

#rule dlc_analyze_videos:
dlc_model_configfile_path : "/lisc/scratch/neurobiology/zimmer/jalaja/DLC_models/autoscope_final-jalaja-2024-07-03/config.yaml"
network_string : "DLC_resnet50_autoscope_finalJul3-trainset95shuffle1_1030000" # You might need to run the code to find out how the string looks like

#rule create_centerline:
# rule create centerline
nose : "nose" # how was the nose annotated as in DLC model? e.g. head, nose, Head, Nose, etc..
tail : "tail" # how was the tail annotated as in DLC model?
num_splines : 100
number_of_neighbours : 1
fill_with_DLC : 1

#annotate ventral side in worm
ventral: "left"

#rule annotate_behaviour:
pca_model_path : "/lisc/scratch/neurobiology/zimmer/jalaja/behaviour/Autoscope/pca_model/1745_20230227_eigenworm_PCA_bodypart_30_to_80.pkl"
initial_segment : 30
final_segment : 80
window : 30

turn_threshold: 0.5

#binarisation threshold for PCA reverse/forward annotation
upper_threshold: "0.0000001"  #my findetuned thresholds
lower_threshold: "-0.000001"

#pharynx tracking
crop_size_pharynx: 200
pharynx: "pharynx" # how was the pharynx annotated as in DLC model?
dlc_model_configfile_path_track_pumps: "/lisc/scratch/neurobiology/zimmer/stoll/code/pharynxpump_network_selected_frames-stoll-2024-04-17/config.yaml"
network_string_pharynx: "DLC_resnet50_pharynxpump_network_selected_framesApr17shuffle1_910000"
