import os
import glob

DATASETS = glob.glob("*/*w*/*Ch0*/")

output_folder_name = 'output/'

# Create a unique output folder for each dataset
for dataset in DATASETS:
    output_folder = os.path.join(dataset, output_folder_name)  # Append 'output' to each dataset path
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)  # Create the folder if it doesn't exist

# Prepend '/output' to each dataset path to ensure processed data goes into the output folder
DATASETS_OUTPUT = glob.glob("*/*w*/*Ch0*/" + output_folder_name)

# background_img = glob.glob("*/background/*background*")[0]

print(DATASETS)

rule targets:
    input:
        binary_mask = expand("{datasets_output}raw_stack_mask.btf", datasets_output=DATASETS_OUTPUT),
        coil_mask = expand("{datasets_output}raw_stack_background_subtracted_coil_segmented_mask.btf", datasets_output=DATASETS_OUTPUT),
        downsampled_avi = expand("{datasets_output}raw_stack_downsampled.avi", datasets_output=DATASETS_OUTPUT),
        behaviour_annotation = expand("{datasets_output}beh_annotation.csv", datasets_output=DATASETS_OUTPUT),
        turn_annotation = expand("{datasets_output}turn_annotation.csv", datasets_output=DATASETS_OUTPUT),
        worm_movie = expand("{datasets_output}worm_movie.avi", datasets_output=DATASETS_OUTPUT),
        chemotaxis_overview = expand("{datasets_output}chemotaxis_overview.png", datasets_output=DATASETS_OUTPUT),
        principal_components = expand("{datasets_output}principal_components.csv", datasets_output=DATASETS_OUTPUT),
        output_skel_X = expand("{datasets_output}skeleton_skeleton_X_coords.csv", datasets_output=DATASETS_OUTPUT),
        output_skel_Y = expand("{datasets_output}skeleton_skeleton_Y_coords.csv", datasets_output=DATASETS_OUTPUT),
        output_spline_X = expand("{datasets_output}skeleton_spline_X_coords.csv", datasets_output=DATASETS_OUTPUT),
        output_spline_Y = expand("{datasets_output}skeleton_spline_Y_coords.csv", datasets_output=DATASETS_OUTPUT),
        corrected_head = expand("{datasets_output}skeleton_corrected_head_coords.csv", datasets_output=DATASETS_OUTPUT),
        corrected_tail = expand("{datasets_output}skeleton_corrected_tail_coords.csv", datasets_output=DATASETS_OUTPUT),
        cropped_pharynx = expand("{datasets_output}cropped_pharynx_video.avi", datasets_output=DATASETS_OUTPUT)

rule ometiff2bigtiff:
    input:
        raw_img = "{datasets_output}raw_stack.btf",
        background_img = background_img
    params:
        function = "stack_subtract_background",
        do_inverse = config["do_inverse"]
    output:
        background_subtracted_img = "{datasets_output}background_subtracted.btf"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            params.function,
            '-i', str(input.raw_img),
            '-o', str(output.background_subtracted_img),
            '-bg', str(input.background_img),
            '-invert', str(params.do_inverse)
        ])

rule unet_predict_and_filter:
    input:
        btf_file = "{datasets_output}raw_stack.btf"
    params:
        model = config["unet_segmentation_model"],
        filter_prediction = config["filter_prediction"],
        scale = 0.301
    output:
        btf_file = "{datasets_output}raw_stack_mask.btf"
    shell:
        """
        source /lisc/app/conda/miniconda3/bin/activate /lisc/scratch/neurobiology/zimmer/schaar/.conda/envs/unet_server_3
        python /lisc/scratch/neurobiology/zimmer/schaar/code/github/unet_pytorch/Pytorch-UNet/predict.py \
            --model {params.model} \
            --input_file_path {input.btf_file} \
            --output_file_path {output.btf_file} \
            --filter_mask {params.filter_prediction} \
            --scale {params.scale}
        """
rule coil_unet:
    input:
        btf_file = "{datasets_output}raw_stack_mask.btf",
        background_subtracted_img = "{datasets_output}background_subtracted.btf"
    params:
        function = "unet_segmentation_contours_with_children",
        weights_path = config["coil_unet_weights"]
    output:
        coil_unet_prediction = "{datasets_output}raw_stack_mask_coil_segmented.btf"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            params.function,
            '-bi', str(input.btf_file),
            '-ri', str(input.background_subtracted_img),
            '-o', str(output.coil_unet_prediction),
            '-w', str(params.weights_path)
        ])

rule binarize_coil:
    input:
        coil_unet_prediction = "{datasets_output}raw_stack_mask_coil_segmented.btf"
    params:
        function = "stack_make_binary",
        threshold = config["coil_threshold"],
        max_value = config["coil_new_value"]
    output:
        binary_img = "{datasets_output}raw_stack_background_subtracted_coil_segmented_mask.btf"

    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            params.function,
            '-i', str(input.coil_unet_prediction),
            '-o', str(output.binary_img),
            '-th', str(params.threshold),
            '-max_val', str(params.max_value)
        ])
