__default__:
    time: 0-08:00:00
    partition: basic
    nodes: 1
    cpus_per_task: 8
    mem: 64G
    disk_mb: 8000
    mem_mb: 8000
    output: log/log_%x_%A_%a_%j.out
    gres:

chemotaxis_analysis:
    time: 0-08:00:00
    partition: basic
    nodes: 1
    cpus_per_task: 24
    mem: 64G
    disk_mb: 8000
    mem_mb: 8000
    output: log/log_%x_%A_%a_%j.out
    gres:  

tiff2avi:
    time: 0-08:00:00
    partition: basic
    nodes: 1
    cpus_per_task: 8
    mem: 64G
    disk_mb: 8000
    mem_mb: 8000
    output: log/log_%x_%A_%a_%j.out
    gres:

dlc_analyze_videos:
    time: 0-08:00:00
    partition: basic,gpu
    mem: 64G
    cpus_per_task: 24
    output: log/log_%x_%A_%a_%j.out
    gres: shard:32

create_centerline:
    time: 0-12:00:00
    partition: basic
    cpus_per_task: 24
    output: log/log_%x_%A_%a_%j.out
    gres:

sam2_segment:
    time: 0-08:00:00
    partition: gpu
    mem: 128G
    gres: shard:32

calc_turns_by_circ:
    time: 0-08:00:00
    partition: basic
    cpus_per_task: 8
    mem: 16G
    output: log/log_%x_%A_%a_%j.out

calc_coils_by_circ:
    time: 0-08:00:00
    partition: basic
    cpus_per_task: 8
    mem: 16G
    output: log/log_%x_%A_%a_%j.out

combine_turn_annotations:
    time: 0-04:00:00
    partition: basic
    cpus_per_task: 4
    mem: 8G
    output: log/log_%x_%A_%a_%j.out

delete_temp_data:
    time: 0-04:00:00
    partition: basic
    cpus_per_task: 2
    mem: 4G
    output: log/log_%x_%A_%a_%j.out

annotate_turns:
    time: 0-04:00:00
    partition: basic
    cpus_per_task: 8
    mem: 16G
    output: log/log_%x_%A_%a_%j.out

annotate_behaviour:
    time: 0-04:00:00
    partition: basic
    cpus_per_task: 16
    mem: 32G
    output: log/log_%x_%A_%a_%j.out
