import os
import glob

DATASETS=glob.glob("*/*w*/*Ch0*/")

background_img = glob.glob("*/background/*background*")[0]

print(DATASETS)

rule targets:
    input:
        #worm_mask = expand("{datasets}raw_stack.btf",datasets=DATASETS),
        #erode_img=expand("{datasets}raw_stack_background_subtracted_mask_eroded.btf",datasets=DATASETS),
        kymogram=expand("{datasets}kymogram.png",datasets=DATASETS),
        ehtogram=expand("{datasets}ehtogram.png",datasets=DATASETS),
        ED_plot=expand("{datasets}distance_plot.png",datasets=DATASETS),
        principal_components=expand("{datasets}principal_components.csv",datasets=DATASETS),
        output_skel_X=expand("{datasets}skeleton_skeleton_X_coords.csv",datasets=DATASETS),
        output_skel_Y=expand("{datasets}skeleton_skeleton_Y_coords.csv",datasets=DATASETS),
        output_spline_X=expand("{datasets}skeleton_spline_X_coords.csv",datasets=DATASETS),
        output_spline_Y=expand("{datasets}skeleton_spline_Y_coords.csv",datasets=DATASETS),
        corrected_head=expand("{datasets}skeleton_corrected_head_coords.csv",datasets=DATASETS),
        corrected_tail=expand("{datasets}skeleton_corrected_tail_coords.csv",datasets=DATASETS),
        # final_img = expand("{files}_AVG_background_subtracted_normalised_unet_segmented_weights_5358068_1_mask_coil_segmented_mask.btf",files=FILES),
        # # Maybe the avi is not needed because itself it is a requirement for final_img
        # avi = expand("{files}_AVG_background_subtracted.avi", files=FILES),
        # spline = expand("{files}_skeleton_spline_K.csv", files=FILES),
        merged_spline_file = expand("{datasets}skeleton_merged_spline_data.csv", datasets=DATASETS)
        #behaviour_annotation = expand("{datasets}beh_annotation.csv", datasets=DATASETS),
        # #speed_file= expand("{files}_raw_worm_speed.csv", files=FILES),
        # #speed_file = expand("{bh_folder}/raw_worm_speed.csv", bh_folder=BH_FOLDERS) #This is not actually produced!
        #figure = expand("{datasets}behavioral_summary_figure.pdf", datasets=DATASETS),  #This is not actually produced!


rule ometiff2bigtiff:
    input:
        #list_of_ometiff_files ="{datasets}/{group}.ome.tif" I don't know how to do this
        script = "/scratch/neurobiology/zimmer/schaar/code/github/imutils/imutils/imutils/src/imutils_parser.py",
    params:
        function = "ometiff2bigtiff"
    output:
        btf_file = "{datasets}raw_stack.btf" #{files}raw_stack.btf"
    shell:
        #TODO: Change back to what it was, without the dirname thing
        """
        DIR=$(dirname {output.btf_file})
        echo $DIR
        python {input.script} {params.function} -path $DIR -output_filename {output.btf_file}
        """


rule subtract_background:
    input:
        raw_img ="{datasets}raw_stack.btf",
        background_img = background_img
    params:
        function = "stack_subtract_background",
        do_inverse = config["do_inverse"]
    output:
        background_subtracted_img ="{datasets}raw_stack_background_subtracted.btf"
    run:
        from imutils.src import imutils_parser_main
        print("test")
        imutils_parser_main.main([
            params.function,
            '-i', str(input.raw_img),
            '-o', str(output.background_subtracted_img),
            '-bg', str(input.background_img),
            '-invert', str(params.do_inverse),
        ])

        #"python {input.script} {params.function} -i {input.raw_img} -o {output.background_subtracted_img} -bg {input.background_img} -invert {params.do_inverse}"


rule normalize_img:
    input:
        input_img = "{datasets}raw_stack_background_subtracted.btf"
    params:
        function = "stack_normalise",
        alpha = config["alpha"],
        beta = config["beta"]
    output:
        normalised_img = "{datasets}raw_stack_AVG_background_subtracted_normalised.btf"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            params.function,
            '-i', str(input.input_img),
            '-o', str(output.normalised_img),
            '-a', str(params.alpha),
            '-b', str(params.beta),
        ])

        #"python {input.script} {params.function} -i {input.input_img} -o {output.normalised_img} -a {params.alpha} -b {params.beta}"


rule make_contour_based_binary:
    input:
        input_img ="{datasets}raw_stack_AVG_background_subtracted_normalised.btf"
    params:
        function = "make_contour_based_binary",
        threshold = config["threshold"],
        max_value = config["max_value"],
        blur = config["blur"], #blur must be odd
        contour_size = config["contour_size"],
        tolerance = config["tolerance"],
        inner_contour_to_fill = config["inner_contour_to_fill"]
    output:
        #I think I could write {params.lower_threshold} in the binary_img string, so that it is not hard coded.
        binary_img = "{datasets}raw_stack_background_subtracted_mask.btf"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            str(params.function),
            '-i', str(input.input_img),
            '-o', str(output.binary_img),
            '-blur', str(params.blur),
            '-th', str(params.threshold),
            '-max_val', str(params.max_value),
            '-cs', str(params.contour_size),
            '-t', str(params.tolerance),
            '-ics', str(params.inner_contour_to_fill),
        ])

        #"python {input.script} {params.function} -i {input.input_img} -o {output.binary_img} -blur {params.blur} -th {params.threshold} -max_val {params.max_value} -cs {params.contour_size} -t {params.tolerance} -ics {params.inner_contour_to_fill}"


rule coil_unet:
    input:
        binary_input_img = "{datasets}raw_stack_background_subtracted_mask.btf",
        raw_input_img="{datasets}raw_stack_AVG_background_subtracted_normalised.btf"
    params:
        function = "unet_segmentation_contours_with_children",
        weights_path= config["coil_unet_weights"]#"/scratch/neurobiology/zimmer/ulises/code/unet-master/data/2023_worm_coiled_segmentation/training_results/5910044_0_w_validation_2batchsize_500steps_100epochs_5patience/unet_master.hdf5",
        #network_name="5910044_0"
    output:
        coil_unet_prediction = "{datasets}raw_stack_background_subtracted_mask_coilnet.btf"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            params.function,
            '-bi', str(input.binary_input_img),
            '-ri', str(input.raw_input_img),
            '-o', str(output.coil_unet_prediction),
            '-w', str(params.weights_path),
        ])
        #"python {input.script} {params.function} -bi {input.binary_input_img} -ri {input.raw_input_img} -o {output.coil_unet_prediction} -w {params.weights_path}"

rule binarize_coil:
    input:
        input_img = "{datasets}raw_stack_background_subtracted_mask_coilnet.btf"
    params:
        function = "stack_make_binary",
        threshold = config["coil_threshold"], # 240
        max_value = config["coil_new_value"] # 255
    output:
        binary_img = "{datasets}raw_stack_background_subtracted_mask_coilnet_binarized.btf"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            str(params.function),
            '-i', str(input.input_img),
            '-o', str(output.binary_img),
            '-th', str(params.threshold),
            '-max_val', str(params.max_value),
        ])

        #"python {input.script} {params.function} -i {input.input_img} -o {output.binary_img} -th {params.threshold} -max_val {params.max_value}"

rule tiff2avi:
    input:
        input_img = "{datasets}raw_stack.btf"
    params:
        function = "tiff2avi",
        fourcc = config["fourcc"],
        fps = config["fps"]
    output:
        avi = "{datasets}raw_stack.avi"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            params.function,
            '-i', str(input.input_img),
            '-o',str(output.avi),
            '-fourcc', str(params.fourcc),
            '-fps', str(params.fps),
        ])

        #"python {input.script} {params.function} -i {input.input_img} -o {output.avi} -fourcc {params.fourcc} -fps {params.fps}" #!


rule downsample_for_DLC:
    input:
        script = "/scratch/neurobiology/zimmer/schaar/code/github/imutils/imutils/imutils/src/downsample_script_512.py",
        avi = "{datasets}raw_stack.avi"
    params:
        fps = config["fps"]
    output:
        downsampled_avi = "{datasets}raw_stack_downsampled.avi"
    run:
        if config["downsample_for_DLC"] == 1:
            shell("python {input.script} --video {input.avi} --output {output.downsampled_avi} --fps {params.fps} ")
        else:
            touch("{output.downsampled_avi}")  # Create an empty file to continue with pipeline
            print("Empty downsampled_avi file created to continue pipeline.")
'''
#needs other conda environment activation since dlc not installed in ulises environment and also packet colisions
rule dlc_analyze_videos:
    input:
        downsampled_avi = "{datasets}raw_stack_downsampled.avi",
        avi = "{datasets}raw_stack.avi"
    params:
        dlc_model_configfile_path = config["dlc_model_configfile_path"],
        network_string = config["network_string"],
        avi_used= "{datasets}raw_stack_downsampled.avi" if (config["downsample_for_DLC"] == 1) else "{datasets}raw_stack.avi"
    #TODO: run conda properly, instead of activating it in the shell. # conda: "/scratch/neurobiology/zimmer/.conda/envs/HR_tracker"
    output:
        #hdf5_file = "{datasets}raw_stack"+config["network_string"]+".h5"
        hdf5_file = "{datasets}raw_stack_downsampled"+config["network_string"]+".h5" if (config["downsample_for_DLC"] == 1) else "{datasets}raw_stack"+config["network_string"]+".h5"
    run:
        from imutils.src import DLC_analyze_videos

        DLC_analyze_videos.main([
            '-path_config_file', str(params.dlc_model_configfile_path),
            '-videofile_path', str(params.avi_used),
        ])
'''

rule dlc_analyze_videos:
    input:
        script = "/scratch/neurobiology/zimmer/schaar/code/autoscope_ulises/packages/other/cluster_analyze_videos.py", #put this in environment package
        downsampled_avi = "{datasets}raw_stack_downsampled.avi",
        avi = "{datasets}raw_stack.avi"
    params:
        dlc_model_configfile_path = config["dlc_model_configfile_path"],
        network_string = config["network_string"],
        avi_used= "{datasets}raw_stack_downsampled.avi" if (config["downsample_for_DLC"] == 1) else "{datasets}raw_stack.avi"
    #TODO: run conda properly, instead of activating it in the shell. # conda: "/scratch/neurobiology/zimmer/.conda/envs/HR_tracker"
    output:
        #hdf5_file = "{datasets}raw_stack"+config["network_string"]+".h5"
        hdf5_file = "{datasets}raw_stack_downsampled"+config["network_string"]+".h5" if (config["downsample_for_DLC"] == 1) else "{datasets}raw_stack"+config["network_string"]+".h5"
    shell:
        """
        source /apps/conda/miniconda3/bin/activate /scratch/neurobiology/zimmer/.conda/envs/HR_tracker
        python {input.script} -path_config_file {params.dlc_model_configfile_path} -videofile_path {params.avi_used}
        """


# # rule dlc_label_videos:
# #     input:
# #         script = ,
# #         input_avi =
# #     params:
# #         dlc_model_configfile_path = ""
# #     output:
# #         labeled_video = ""
# #     shell:
# #         ""
# #
# This rule erodes the binary mask from the background-subtracted image for a specified number of iterations and saves the eroded image.

rule erode_binary_mask:
    input:
        binary_img = "{datasets}raw_stack_background_subtracted_mask_coilnet_binarized.btf"
    params:
        iter =  config['iterations']
    output:
        erode_img = "{datasets}raw_stack_background_subtracted_mask_eroded.btf"
    run:
        import pandas as pd
        import numpy as np
        import tifffile as tiff
        from scipy import ndimage

        with tiff.TiffFile(input.binary_img, multifile=False) as tif, tiff.TiffWriter(output.erode_img, bigtiff=True) as output_tif:
             for i, page in enumerate(tif.pages):
                 img = page.asarray()
                 eroded_img = ndimage.binary_erosion(img,iterations=params.iter)
                 eroded_img = eroded_img * 255
                 eroded_img = eroded_img.astype(np.uint8)
                 #eroded_img = np.array(eroded_img, dtype=np.uint8)
                 # save as a btf
                 output_tif.write(eroded_img,photometric='minisblack',contiguous=True)

rule create_centerline:
    input:
        #TODO: Try ancient() to see if I can avoid re-running when the script is modified
        input_binary_img = "{datasets}raw_stack_background_subtracted_mask_eroded.btf",
        hdf5_file = "{datasets}raw_stack_downsampled"+config["network_string"]+".h5" if (config["downsample_for_DLC"] == 1) else "{datasets}raw_stack"+config["network_string"]+".h5"
        #hdf5_file = "{datasets}raw_stack"+config["network_string"]+".h5" #"AVG_background_subtracted_normalisedDLC_resnet50_wbfm_nose_tailJan4shuffle1_1030000.h5"

    params:
        csv_output_path = "{datasets}",  # This cant go into inputs because it is not a file
        number_of_neighbours = "1",
        nose = config['nose'],
        tail = config['tail'],
        num_splines = config['num_splines'],
        downsample_for_DLC= config["downsample_for_DLC"],
        fill_with_DLC = "1" # TODO: Improve so argparse takes boolean

    output :
        output_skel_X = "{datasets}skeleton_skeleton_X_coords.csv",
        output_skel_Y = "{datasets}skeleton_skeleton_Y_coords.csv",
        output_spline_K = "{datasets}skeleton_spline_K.csv",
        output_spline_X = "{datasets}skeleton_spline_X_coords.csv",
        output_spline_Y = "{datasets}skeleton_spline_Y_coords.csv",
        corrected_head = "{datasets}skeleton_corrected_head_coords.csv",
        corrected_tail = "{datasets}skeleton_corrected_tail_coords.csv"
    run:
        from centerline.dev import head_and_tail

        head_and_tail.main([
            '-i', str(input.input_binary_img),
            '-h5', str(input.hdf5_file),
            '-o', str(params.csv_output_path),
            '-nose', str(params.nose),
            '-tail', str(params.tail),
            '-num_splines', str(params.num_splines),
            '-n', str(params.number_of_neighbours),
            '-dlc', str(params.fill_with_DLC),
            '-ds', str(params.downsample_for_DLC),
        ])

        #"python {input.script} -i {input.input_binary_img} -h5 {input.hdf5_file} -o {params.csv_output_path} -nose {params.nose} -tail {params.tail} -num_splines {params.num_splines} -n {params.number_of_neighbours} -dlc {params.fill_with_DLC} -ds {params.downsample_for_DLC}"

rule reformat_skeleton_files:
    input:
        spline_K= "{datasets}skeleton_spline_K.csv",
        spline_X= "{datasets}skeleton_spline_X_coords.csv",
        spline_Y= "{datasets}skeleton_spline_Y_coords.csv"
    output:
        merged_spline_file = "{datasets}skeleton_merged_spline_data.csv",
    run:
        from centerline.dev import reformat_skeleton_files

        reformat_skeleton_files.main([
            '-i_K', str(input.spline_K),
            'i_X', str(input.spline_X),
            '-i_Y', str(input.spline_Y),
            '-o', str(output.merged_spline_file),
        ])


        #"python {input.script} -i_K {input.spline_K} -i_X {input.spline_X} -i_Y {input.spline_Y} -o {output.merged_spline_file}"


rule annotate_behaviour:
    input:
        script = "/scratch/neurobiology/zimmer/schaar/code/github/curvature/curvature/curvature/src/annotate_reversals_snakemake.py",
        curvature_file = "{datasets}skeleton_spline_K.csv"
    params:
        #pca_model_path = "/scratch/neurobiology/zimmer/ulises/code/curvature/curvature/models/1651_20220810_eigenworm_PCA_bodypart_30_to_80.pkl"
        pca_model_path = config["pca_model_path"],
        #features should be added here, and maybe rolling mean (or use averaged splineK instead)
        initial_segment = config["initial_segment"],
        final_segment = config["final_segment"],
        window = config["window"]
    output:
        principal_components = "{datasets}principal_components.csv",
        behaviour_annotation = "{datasets}beh_annotation.csv"

    run:
        from curvature.src import annotate_reversals_snakemake

        annotate_reversals_snakemake.main([
            '-i', str(input.curvature_file),
            'pca', str(params.pca_model_path),
            '-i_s', str(params.initial_segment),
            '-f_s', str(params.final_segment),
            '-win', str(params.window),
            '-o_pc', str(output.principal_components),
            '-o_bh', str(output.behaviour_annotation),
        ])

        #"python {input.script} -i {input.curvature_file} -pca {params.pca_model_path} -i_s {params.initial_segment} -f_s {params.final_segment} -win {params.window} -o_pc {output.principal_components} -o_bh {output.behaviour_annotation}"

rule create_plots:
    input:
        script="/scratch/neurobiology/zimmer/schaar/code/github/autoscope_analysis_extras/DLC_track_pharynx_egg/scripts/plot_autoscope/plot_autoscope_data.py",
        behaviour_annotation="{datasets}beh_annotation.csv",
        spline_K= "{datasets}skeleton_spline_K.csv",
        worm_pos= "{datasets}worm_pos.txt",
        stage_pos= "{datasets}stage_pos.yaml"
    output:
        kymogram= "{datasets}kymogram.png",
        ehtogram= "{datasets}ehtogram.png",
        ED_plot= "{datasets}distance_plot.png"
    shell:
        "python {input.script} --beh_annotation {input.behaviour_annotation} --skeleton_spline {input.spline_K} --worm_pos {input.worm_pos} --stage_pos {input.stage_pos}"
