# Video processing parameters
fourcc: 0
fps: 10
factor_px_to_mm: '0.00962'

# Model paths and settings
dlc_model_configfile_path: /lisc/scratch/neurobiology/zimmer/schaar/code/DLC/population_nose_neck_vulva_tail_elpiniki_chanuka_itamar-elpi-2024-09-23/config.yaml
network_string: DLC_resnet50_population_nose_neck_vulva_tail_elpiniki_chanuka_itamarSep23shuffle2_1030000
pca_model_path: /lisc/scratch/neurobiology/zimmer/autoscope/trained_models/PCA_models/equi_distance_centerline_seg_10_40.pkl

# SAM2 parameters
downsample_factor: 0
batch_size: 200

# Worm detection parameters
min_worm_area: 400
max_worm_area: 1000
min_worm_lenght: 83  # Note: there's a typo in 'length'

# Annotation parameters
nose: head
tail: tail
num_splines: 20
initial_segment: 9
final_segment: 39

#preprocess spline
relative_spacing: 2.0  # 2% of skeleton length
num_sampled_points: 10000
smoothing: 0
time_sigma: 2.0
spatial_sigma: 1.0
max_columns: 0 #dynamic mode - cuts skelleton where nan content increases 50%+

window: 10
min_round_threshold: 0.55
max_round_threshold: 0.99
upper_threshold: '0.000001'
lower_threshold: '-0.00001'

diffusion_time_offset: 3600 #3600 seconds = default of 1 hour

# Data file paths
conc_gradient_array: /lisc/scratch/neurobiology/zimmer/schaar/diffusion/benzaldehyde_0.07/interpolated_concentration_array.npy
distance_array: /lisc/scratch/neurobiology/zimmer/schaar/diffusion/benzaldehyde_0.07/interpolated_distance_array.npy