#files: [""]
  #["data/IL40_worm1/worm_Ch0-BH/2022-09-13_14-50_IL40_worm1_Ch0-BHbigtiff",
        #"data/IL40_worm2/worm_Ch0-BH/2022-09-13_15-25_IL40_worm2_Ch0-BHbigtiff",
        #"data/ZIM2156_worm2/worm_Ch0-BH/2022-09-13_15-08_ZIm2156_worm2_Ch0-BHbigtiff"]#, "2022-09-13_15-08_ZIm2156_worm2_long_Ch0-BHbigtiff"]

#In the future it would be better either files or folder.
#Even files is not file atm, but file.basename

#rule create_background
radius: 100

#rule subtract background
do_inverse: True

#Choose here if you want to do the contour based binarization. If you want default binarization with a simple threshold, set this to False
contour_based_binarization: True

#rule normalise
alpha: 0
beta: 255

# rule binarize and rule binarize with contours parameters:
threshold : 20
max_value : 255

# rule binarize with contours parameters:
#IMPORTANT!: threshold and max_value above are also parameters for this rule!!
blur_gaussian: 1 #needs to be odd
blur : 15 #needs to be odd
contour_size : 15000
tolerance : 0.5                     
inner_contour_to_fill : 2000

# rule tiff2avi:
fourcc : 0
fps : 80

downsample_for_DLC : 1  #downdownsample_for_DLC 1 = yes 0 = no -> will downsample video to 512 for DLC to track head and tail properly

#rule crop_worm_from_tiff
crop_size : 600,600

#rule dlc_analyze_videos:

dlc_model_configfile_path : "/lisc/scratch/neurobiology/zimmer/zidaric/code/dlc_projects/nn512_nose_tail/20231126_nn512_nose_tail-sam/config.yaml"
network_string : "DLC_mobnet_35_20231124_nose_tailNov24shuffle1_900000" # You might need to run the code to find out how the string looks like

#rule erode_binary_mask:
iterations : 8

#rule create_centerline:
# rule create centerline
nose : "nose" # how was the nose annotated as in DLC model? e.g. head, nose, Head, Nose, etc..
tail : "tail" # how was the tail annotated as in DLC model?
num_splines : 100
number_of_neighbours : 1
fill_with_DLC : 1

#rule annotate_behaviour:
pca_model_path : "/scratch/neurobiology/zimmer/jalaja/behaviour/Autoscope/pca_model/1745_20230227_eigenworm_PCA_bodypart_30_to_80.pkl"
initial_segment : 30
final_segment : 80
window : 10

