import os
import glob


DATASETS=glob.glob("data/*w*/*Ch0-BH/")
print("These are the datasets: ", DATASETS)

background_img = glob.glob("data/background/*background*BH*/*AVG*background*")[0]
print("This is the background image: ", background_img)

rule targets:
    input:
        #raw_stack = expand("{datasets}raw_stack.btf", datasets=DATASETS),
        bg_subtracted = expand("{datasets}raw_stack_AVG_background_subtracted.btf", datasets=DATASETS),
        normalised = expand("{datasets}raw_stack_AVG_background_subtracted_normalised.btf", datasets=DATASETS),
        worm_unet = expand("{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented.btf", datasets=DATASETS),
        coil_unet_mask = expand("{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented_mask_coil_segmented_mask.btf", datasets=DATASETS),
        spline_K = expand("{datasets}skeleton_spline_K.csv", datasets=DATASETS),
        spline_K_signed = expand("{datasets}skeleton_spline_K_signed.csv", datasets=DATASETS),
        spline_K_signed_avg = expand("{datasets}skeleton_spline_K_signed_avg.csv", datasets=DATASETS),
        spline_X_avg = expand("{datasets}skeleton_spline_X_coords_avg.csv", datasets=DATASETS),
        hilbert = expand("{datasets}hilbert_inst_amplitude.csv", datasets=DATASETS),
        fft_xf = expand("{datasets}fft_xf.csv", datasets=DATASETS),
        merged_spline_data = expand("{datasets}skeleton_merged_spline_data_avg.csv", datasets=DATASETS),
        beh_annotation = expand("{datasets}beh_annotation.csv", datasets=DATASETS),
        turn_annotation = expand("{datasets}turns_annotation.csv", datasets=DATASETS),
        self_touch = expand("{datasets}self_touch.csv", datasets=DATASETS),
        speed = expand("{datasets}raw_worm_speed.csv", datasets=DATASETS),
        signed_speed = expand("{datasets}signed_worm_speed.csv", datasets=DATASETS),
        beh_figure= expand("{datasets}behavioral_summary_figure.pdf", datasets=DATASETS)

# rule ometiff2bigtiff:
#     input:
#         script = "/scratch/neurobiology/zimmer/ulises/code/imutils/imutils/src/imutils_parser.py",
#         #list_of_ometiff_files ="{datasets}/{group}.ome.tif" I don't know how to do this
#     params:
#         function = "ometiff2bigtiff"
#     output:
#         btf_file = "{datasets}raw_stack.btf"
#     shell:
#         "python {input.script} {params.function} -path {wildcards.datasets} -output_filename {output.btf_file}"

rule subtract_background:
    input:
        script = ancient("/scratch/neurobiology/zimmer/ulises/code/imutils/imutils/src/imutils_parser.py"),
        raw_img  = "{datasets}raw_stack.btf",
        #raw_img ="{datasets}raw_stack.btf",
        background_img = background_img
    params:
        function = "stack_subtract_background",
        do_inverse = config["do_inverse"]
    output:
        background_subtracted_img ="{datasets}raw_stack_AVG_background_subtracted.btf"
    shell:
        "python {input.script} {params.function} -i {input.raw_img} -o {output.background_subtracted_img} -bg {input.background_img} -invert {params.do_inverse}"

rule normalize_img:
    input:
        script = ancient("/scratch/neurobiology/zimmer/ulises/code/imutils/imutils/src/imutils_parser.py"),
        input_img = "{datasets}raw_stack_AVG_background_subtracted.btf"
    params:
        function = "stack_normalise",
        alpha = config["alpha"],
        beta = config["beta"]
    output:
        normalised_img = "{datasets}raw_stack_AVG_background_subtracted_normalised.btf"
    shell:
        "python {input.script} {params.function} -i {input.input_img} -o {output.normalised_img} -a {params.alpha} -b {params.beta}"

rule worm_unet:
    input:
        script = ancient("/scratch/neurobiology/zimmer/ulises/code/imutils/imutils/src/imutils_parser.py"),
        input_img = "{datasets}raw_stack_AVG_background_subtracted_normalised.btf"
    params:
        function  = "unet_segmentation_stack",
        weights_path = config["worm_unet_weights"],#"/scratch/neurobiology/zimmer/ulises/code/unet-master/data/2022_08_12_worm_segmentation_all_worms_good_background_normalized/training_results/5358068_1_w_validation_1batchsize_500steps_100epochs_5patience/unet_master.hdf5",
        #network_name = config["worm_unet_network_name"]# '5358068_1'
    output:
        worm_unet_prediction = "{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented.btf"
    shell:
        "python {input.script} {params.function} -i {input.input_img} -o {output.worm_unet_prediction} -w {params.weights_path}"

rule binarize:
    input:
        script = ancient("/scratch/neurobiology/zimmer/ulises/code/imutils/imutils/src/imutils_parser.py"),
        input_img = "{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented.btf"
    params:
        function = "stack_make_binary",
        threshold = config["threshold"],
        max_value = config["max_value"]
    output:
        binary_img = "{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented_mask.btf"
    shell:
        "python {input.script} {params.function} -i {input.input_img} -o {output.binary_img} -th {params.threshold} -max_val {params.max_value}"

rule coil_unet:
    input:
        script = ancient("/scratch/neurobiology/zimmer/ulises/code/imutils/imutils/src/imutils_parser.py"), #fix this
        binary_input_img = "{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented_mask.btf",
        raw_input_img = "{datasets}raw_stack_AVG_background_subtracted_normalised.btf"
    params:
        function = "unet_segmentation_contours_with_children",
        weights_path= config["coil_unet_weights"]#"/scratch/neurobiology/zimmer/ulises/code/unet-master/data/2023_worm_coiled_segmentation/training_results/5910044_0_w_validation_2batchsize_500steps_100epochs_5patience/unet_master.hdf5",
        #network_name="5910044_0"
    output:
        coil_unet_prediction = "{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented_mask_coil_segmented.btf"
    shell:
        "python {input.script} {params.function} -bi {input.binary_input_img} -ri {input.raw_input_img} -o {output.coil_unet_prediction} -w {params.weights_path}"


rule binarize_coil:
    input:
        script = ancient("/scratch/neurobiology/zimmer/ulises/code/imutils/imutils/src/imutils_parser.py"),
        input_img = "{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented_mask_coil_segmented.btf"
    params:
        function = "stack_make_binary",
        threshold = config["coil_threshold"], # 240
        max_value = config["coil_new_value"] # 255
    output:
        binary_img = "{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented_mask_coil_segmented_mask.btf"
    shell:
        "python {input.script} {params.function} -i {input.input_img} -o {output.binary_img} -th {params.threshold} -max_val {params.max_value}"

rule tiff2avi:
    input:
        script = ancient("/scratch/neurobiology/zimmer/ulises/code/imutils/imutils/src/imutils_parser.py"),
        input_img = "{sample}raw_stack_AVG_background_subtracted_normalised.btf"
    params:
        function = "tiff2avi",
        fourcc = config["fourcc"], #"0",
        fps = config["fps"] # "167"
    output:
        avi = "{sample}raw_stack_AVG_background_subtracted_normalised.avi"
    shell:
        "python {input.script} {params.function} -i {input.input_img} -o {output.avi} -fourcc {params.fourcc} -fps {params.fps}" #!

rule dlc_analyze_videos:
    input:
        script = "/scratch/neurobiology/zimmer/ulises/code/dlc_utils_code/cluster_analyze_videos.py", #python code would be better?
        input_avi = "{datasets}raw_stack_AVG_background_subtracted_normalised.avi"
    params:
        dlc_model_configfile_path = config["dlc_model_configfile_path"],
        dlc_network_string = config["dlc_network_string"] # Is this used?
    output:
        hdf5_file = "{datasets}raw_stack_AVG_background_subtracted_normalised"+config["dlc_network_string"]+".h5"
    shell:
        #TODO: run conda properly, instead of activating it in the shell. # conda: "/scratch/neurobiology/zimmer/.conda/envs/HR_tracker"
        """
        source /apps/conda/miniconda3/bin/activate /scratch/neurobiology/zimmer/.conda/envs/HR_tracker
        python {input.script} -path_config_file {params.dlc_model_configfile_path} -videofile_path {input.input_avi}
        """
# PENDING
# # rule dlc_label_videos:
# #     input:
# #         script = ,
# #         input_avi =
# #     params:
# #         dlc_model_configfile_path = ""
# #     output:
# #         labeled_video = ""
# #     shell:
# #         ""
# #
rule create_centerline:
    input:
        script = ancient("/scratch/neurobiology/zimmer/ulises/code/centerline/centerline/dev/head_and_tail.py"),
        input_binary_img = "{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented_mask_coil_segmented_mask.btf",
        # TODO: should come from the rule dlc_analyze_videos output
        hdf5_file = "{datasets}raw_stack_AVG_background_subtracted_normalised"+config["dlc_network_string"]+".h5"

    params:
        #output_path = "{datasets}", #This is kind of cheating, but works. This might also work directly on the shell {wildcards.datasets}
        number_of_neighbours = "1",
        nose = config['nose'],
        tail = config['tail'],
        num_splines = config['num_splines'],
        fill_with_DLC = "1" # TODO: Improve so agparse takes boolean
    output :
        output_skel_X = "{datasets}skeleton_skeleton_X_coords.csv",
        output_skel_Y = "{datasets}skeleton_skeleton_Y_coords.csv",
        output_spline_K = "{datasets}skeleton_spline_K.csv",
        output_spline_X = "{datasets}skeleton_spline_X_coords.csv",
        output_spline_Y = "{datasets}skeleton_spline_Y_coords.csv",
        corrected_head = "{datasets}skeleton_corrected_head_coords.csv",
        corrected_tail = "{datasets}skeleton_corrected_tail_coords.csv"
    shell:
        "python {input.script} -i {input.input_binary_img} -h5 {input.hdf5_file} -o {wildcards.datasets} -nose {params.nose} -tail {params.tail} -num_splines {params.num_splines} -n {params.number_of_neighbours} -dlc {params.fill_with_DLC}"
# # This rule has not been functional yet because I need to access its config.yaml file and I do not know how
# # For the time being there is a cluster_jobs script
rule invert_curvature_sign:
    input:
        script = "/scratch/neurobiology/zimmer/ulises/code/curvature/curvature/src/invert_curvature_sign.py",
        spline_K = "{datasets}skeleton_spline_K.csv",
        # would be good to ad the config yaml file to input because if it is updated the code should re-run
        #config_yaml_file = os.path.join(os.path.dirname(os.path.dirname("{sample}_skeleton_spline_K.csv")), "config.yaml") #hard to get its path
    # params:
    #     output_path = "{datasets}"
    output:
        spline_K = "{datasets}skeleton_spline_K_signed.csv"
    shell:
        """
        DIR=$(dirname {wildcards.datasets})
        echo $DIR
        python {input.script} -i $DIR
        """

rule average_kymogram:
    input:
        spline_K = "{datasets}skeleton_spline_K_signed.csv"
    params:
        #rolling_mean_type =,
        window = config['averaging_window']
    output:
        spline_K_avg = "{datasets}skeleton_spline_K_signed_avg.csv"
    run:
        import pandas as pd
        df=pd.read_csv(input.spline_K, index_col=None, header=None)
        df=df.rolling(window=params.window, center=True, min_periods=1).mean()
        df.to_csv(output.spline_K_avg, header=None, index=None)
        print('end of python script')

rule average_xy_coords:
    input:
        spline_X= "{datasets}skeleton_spline_X_coords.csv",
        spline_Y= "{datasets}skeleton_spline_Y_coords.csv",
    params:
        #rolling_mean_type =,
        window = config['averaging_window']
    output:
        spline_X_avg= "{datasets}skeleton_spline_X_coords_avg.csv",
        spline_Y_avg= "{datasets}skeleton_spline_Y_coords_avg.csv",
    run:
        import pandas as pd

        df=pd.read_csv(input.spline_X, index_col=None, header=None)
        df=df.rolling(window=params.window, center=True, min_periods=1).mean()
        df.to_csv(output.spline_X_avg, header=None, index=None)

        df=pd.read_csv(input.spline_Y, index_col=None, header=None)
        df=df.rolling(window=params.window, center=True, min_periods=1).mean()
        df.to_csv(output.spline_Y_avg, header=None, index=None)

rule hilbert_transform_on_kymogram:
    input:
        script = "/scratch/neurobiology/zimmer/ulises/code/behavior_analysis/src/hilbert_transform.py",
        spline_K = "{datasets}skeleton_spline_K_signed_avg.csv"
    params:
        fs = config["sampling_frequency"],
        window = config["hilbert_averaging_window"]
    output:
        # wont be created because they the outputs do not have the {sample} root
        hilbert_regenerated_carrier = "{datasets}hilbert_regenerated_carrier.csv",
        hilbert_inst_freq = "{datasets}hilbert_inst_freq.csv",
        hilbert_inst_phase = "{datasets}hilbert_inst_phase.csv",
        hilbert_inst_amplitude = "{datasets}hilbert_inst_amplitude.csv"

    #This $DIR only goes one time up
    shell:
        """
        python {input.script} -i {wildcards.datasets} -kp {input.spline_K} -fs {params.fs} -w {params.window}
        """

rule fast_fourier_transform:
    input:
        script="/scratch/neurobiology/zimmer/ulises/code/centerline/centerline/dev/fourier_functions.py",
        spline_K="{datasets}skeleton_spline_K_signed_avg.csv"
    params:
        # project_folder
        sampling_frequency=config["sampling_frequency"],
        window = config["fft_averaging_window"]
    output:
        y_axis_file = "{datasets}fft_y_axis.csv", #not correct ?
        xf_file = "{datasets}fft_xf.csv"
    #This $DIR only goes one time up
    shell:
        "python {input.script} -i {wildcards.datasets} -kp {input.spline_K} -fps {params.sampling_frequency} -w {params.window}"

rule reformat_skeleton_files:
    input:
        script = "/scratch/neurobiology/zimmer/ulises/code/centerline/centerline/dev/reformat_skeleton_files.py",
        spline_K= "{datasets}skeleton_spline_K_signed_avg.csv", #should have signed spline_K
        spline_X= "{datasets}skeleton_spline_X_coords_avg.csv",
        spline_Y= "{datasets}skeleton_spline_Y_coords_avg.csv",
        #spline_list = ["{sample}_spline_K.csv", "{sample}_spline_X_coords.csv", "{sample}_spline_Y_coords.csv",]

    output:
        merged_spline_file = "{datasets}skeleton_merged_spline_data_avg.csv",

    shell:
        "python {input.script} -i_K {input.spline_K} -i_X {input.spline_X} -i_Y {input.spline_Y} -o {output.merged_spline_file}"

rule annotate_behaviour:
    input:
        script = "/scratch/neurobiology/zimmer/ulises/code/curvature/curvature/src/annotate_reversals_snakemake.py",
        curvature_file = "{datasets}skeleton_spline_K_signed_avg.csv"

    params:
        #pca_model_path = "/scratch/neurobiology/zimmer/ulises/code/curvature/curvature/models/1651_20220810_eigenworm_PCA_bodypart_30_to_80.pkl"
        pca_model_path = config["pca_model"], #"/scratch/neurobiology/zimmer/ulises/code/curvature/curvature/models/1550_20230202_eigenworm_PCA_bodypart_30_to_80.pkl",
        initial_segment = config["initial_segment"],
        final_segment = config["final_segment"],
        window = config["window"]
    output:
        principal_components = "{datasets}principal_components.csv",
        behaviour_annotation = "{datasets}beh_annotation.csv"

    shell :
        "python {input.script} -i {input.curvature_file} -pca {params.pca_model_path} -i_s {params.initial_segment} -f_s {params.final_segment} -win {params.window} -o_pc {output.principal_components} -o_bh {output.behaviour_annotation}"

rule annotate_turns:
    input:
        script = "/scratch/neurobiology/zimmer/ulises/code/curvature/curvature/src/annotate_turns_snakemake.py",
        #principal_components = "{datasets}principal_components.csv"
        spline_K  = "{datasets}skeleton_spline_K_signed_avg.csv"
    params:
        threshold = config["turn_threshold"],
        initial_segment = config["turn_initial_segment"],
        final_segment = config["turn_final_segment"],
        avg_window = config["turn_avg_window"]
    output:
        turns_annotation = "{datasets}turns_annotation.csv"

    shell :
        "python {input.script} -input {input.spline_K} -t {params.threshold} -i_s {params.initial_segment} -f_s {params.final_segment} -avg_window {params.avg_window} -bh {output.turns_annotation}"

rule self_touch:
    input:
        #script = "/scratch/neurobiology/zimmer/ulises/code/behavior_analysis/src/self_touch.py",
        binary_img = "{datasets}raw_stack_AVG_background_subtracted_normalised_worm_segmented_mask.btf"
    params:
        external_area = [7000, 20000],
        internal_area = [100, 2000],
    output:
        self_touch = "{datasets}self_touch.csv"
    run:
        from imutils.src.imfunctions import find_specific_contours_with_specific_children
        from imutils.src.imfunctions import stack_self_touch
        import pandas as pd
        df = stack_self_touch(input.binary_img, params.external_area, params.internal_area)
        df.to_csv(output.self_touch)

rule calculate_parameters:
    #So far it only calculates speed
    input:
        script = "/scratch/neurobiology/zimmer/ulises/code/behavior_analysis/src/calculate_parameters.py", #stage position should be input
        curvature_file = "{datasets}skeleton_spline_K_signed_avg.csv" #This is used as a parameter because it is only used to find the main dir
    output:
        speed_file = "{datasets}raw_worm_speed.csv" # This is never produced, so this will always run
    shell:
        """
        DIR=$(dirname {wildcards.datasets})
        echo $DIR
        python {input.script} -i $DIR
        """

rule save_signed_speed:
    input:
        script = "/scratch/neurobiology/zimmer/ulises/code/behavior_analysis/src/calculate_parameters.py", #stage position should be input
        raw_speed_file = "{datasets}raw_worm_speed.csv",
        behaviour_annotation= "{datasets}beh_annotation.csv"
    output:
        signed_speed_file = "{datasets}signed_worm_speed.csv" # This is never produced, so this will always run
    run:
        import pandas as pd
        raw_speed_df=pd.read_csv(input.raw_speed_file)
        ethogram_df = pd.read_csv(input.behaviour_annotation)
        signed_speed_df = pd.DataFrame()
        signed_speed_df['Raw Speed Signed (mm/s)'] = raw_speed_df['Raw Speed (mm/s)'] * ethogram_df['0'] * -1 # to invert because fwd is -1 in the ethogram
        signed_speed_df.to_csv(output.signed_speed_file)
        print("If the ethogram had a running average and had less values at the start and end, so will the signed speed")

rule make_behaviour_figure:
    input:
        script = "/scratch/neurobiology/zimmer/ulises/code/behavior_analysis/src/make_figure.py",
        curvature_file = "{datasets}skeleton_spline_K_signed_avg.csv",
        pc_file = "{datasets}principal_components.csv",
        # total_curvature_file = "",
        beh_annotation_file = "{datasets}beh_annotation.csv",
        speed_file = "{datasets}signed_worm_speed.csv",
        # track_file = ""
    # params:
    #     curvature_file= "{sample}_skeleton_spline_K.csv",
    #    smooth = True # Choose smooth or raw Kymogram
    output:
        figure = "{datasets}behavioral_summary_figure.pdf" #This is  never produced, so it whill always run
    shell:
        """
        DIR=$(dirname {wildcards.datasets})
        echo $DIR
        python {input.script} -i $DIR
        """
