import os
import glob

DATASETS=glob.glob("*/*w*/*Ch0*/")

output_folder_name='output/'

#Create a unique output folder for each dataset
for dataset in DATASETS:
    output_folder = os.path.join(dataset, output_folder_name)  # Append 'output' to each dataset path
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)  # Create the folder if it doesn't exist

# Prepend '/output' to each dataset path to ensure processed data goes into the output folder
DATASETS_OUTPUT = glob.glob("*/*w*/*Ch0*/" + output_folder_name)    

background_img = glob.glob("*/background/*background*")[0]

print(DATASETS)

rule targets:
    input:
        output_skel_X = expand("{datasets_output}skeleton_skeleton_X_coords.csv",datasets_output=DATASETS_OUTPUT),
        output_skel_Y = expand("{datasets_output}skeleton_skeleton_Y_coords.csv",datasets_output=DATASETS_OUTPUT),
        #output_spline_K = expand("{datasets_output}skeleton_spline_K.csv",datasets_output=DATASETS_OUTPUT),
        #output_spline_X = expand("{datasets_output}skeleton_spline_X_coords.csv",datasets_output=DATASETS_OUTPUT),
        #output_spline_Y = expand("{datasets_output}skeleton_spline_Y_coords.csv",datasets_output=DATASETS_OUTPUT),
        corrected_head = expand("{datasets_output}skeleton_corrected_head_coords.csv",datasets_output=DATASETS_OUTPUT),
        corrected_tail = expand("{datasets_output}skeleton_corrected_tail_coords.csv",datasets_output=DATASETS_OUTPUT),
        merged_spline_file = expand("{datasets_output}skeleton_merged_spline_data.csv",datasets_output=DATASETS_OUTPUT),
        principal_components = expand("{datasets_output}principal_components.csv",datasets_output=DATASETS_OUTPUT),
        #behaviour_annotation = expand("{datasets_output}beh_annotation.csv",datasets_output=DATASETS_OUTPUT)
        #behaviour_annotation1 = expand("{datasets_output}beh_annotation1.csv",datasets_output=DATASETS_OUTPUT),
        behaviour_annotation2 = expand("{datasets_output}beh_annotation2.csv",datasets_output=DATASETS_OUTPUT),
        kymogram = expand("{datasets_output}kymogram.png",datasets_output=DATASETS_OUTPUT),
        ethogram = expand("{datasets_output}ethogram.png",datasets_output=DATASETS_OUTPUT),
        ethogram_led = expand("{datasets_output}ethogram_led.png",datasets_output=DATASETS_OUTPUT),
        kymogram_smooth = expand("{datasets_output}kymogram_smooth.png",datasets_output=DATASETS_OUTPUT),
        rev_duration = expand("{datasets_output}rev_duration_all.xlsx",datasets_output=DATASETS_OUTPUT),
        rev_reaction = expand("{datasets_output}rev_reaction.xlsx",datasets_output=DATASETS_OUTPUT)


'''
rule ometiff2bigtiff:
    input:
        source_path = '{datasets_output}../'
    params:
        function = "ometiff2bigtiff"
    output:
        btf_file = "{datasets_output}raw_stack.btf" #{files}raw_stack.btf"
    run:
        import os
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            params.function,
            '-path', str(input.source_path),
            '-output_filename', str(output.btf_file),
        ])
'''

rule subtract_background:
    input:
        raw_img ="{datasets_output}../raw_stack.btf",
        background_img = background_img
    params:
        function = "stack_subtract_background",
        do_inverse = config["do_inverse"]
    output:
        background_subtracted_img ="{datasets_output}raw_stack_background_subtracted.btf"
    run:
        from imutils.src import imutils_parser_main
        imutils_parser_main.main([
            params.function,
            '-i', str(input.raw_img),
            '-o', str(output.background_subtracted_img),
            '-bg', str(input.background_img),
            '-invert', str(params.do_inverse),
        ])

rule normalize_img:
    input:
        input_img = "{datasets_output}raw_stack_background_subtracted.btf"
    params:
        function = "stack_normalise",
        alpha = config["alpha"],
        beta = config["beta"]
    output:
        normalised_img = "{datasets_output}raw_stack_AVG_background_subtracted_normalised.btf"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            params.function,
            '-i', str(input.input_img),
            '-o', str(output.normalised_img),
            '-a', str(params.alpha),
            '-b', str(params.beta),
        ])

rule make_contour_based_binary:
    input:
        input_img ="{datasets_output}raw_stack_AVG_background_subtracted_normalised.btf"
    params:
        function = "make_contour_based_binary",
        threshold = config["threshold"],
        max_value = config["max_value"],
        blur_gaussian = config["blur_gaussian"],
        blur = config["blur"],
        contour_size = config["contour_size"],
        tolerance = config["tolerance"],
        inner_contour_to_fill = config["inner_contour_to_fill"]
    output:
        #I think I could write {params.lower_threshold} in the binary_img string, so that it is not hard coded.
        binary_img = "{datasets_output}raw_stack_background_subtracted_mask.btf"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            str(params.function),
            '-i', str(input.input_img),
            '-o', str(output.binary_img),
            '-blur', str(params.blur),
            '-th', str(params.threshold),
            '-max_val', str(params.max_value),
            '-cs', str(params.contour_size),
            '-t', str(params.tolerance),
            '-ics', str(params.inner_contour_to_fill),
            '-blur_gaussian',str(params.blur_gaussian),
        ])

rule tiff2avi:
    input:
        input_img = "{datasets_output}../raw_stack.btf"
    params:
        function = "tiff2avi",
        fourcc = config["fourcc"],
        fps = config["fps"]
    output:
        avi = "{datasets_output}raw_stack.avi"
    run:
        from imutils.src import imutils_parser_main

        imutils_parser_main.main([
            params.function,
            '-i', str(input.input_img),
            '-o',str(output.avi),
            '-fourcc', str(params.fourcc),
            '-fps', str(params.fps),
        ])

rule crop_worm_from_tiff:
    input:
        binary_img = "{datasets_output}raw_stack_background_subtracted_mask.btf"
    output:
        cropped_tiff = "{datasets_output}raw_stack_background_subtracted_mask_cropped.btf",
        roi_data = "{datasets_output}roi_data.xlsx"
    params:
        crop_size = config["crop_size"],
        fps = config["fps"]
    run:
        from imutils.src import crop_worm_from_tiff

        crop_worm_from_tiff.main([
            '--binary_stack', str(input.binary_img),
            '--output', str(output.cropped_tiff),
            '--crop_size', str(params.crop_size),
            '--excel_file', str(output.roi_data),
        ])

rule create_avi_from_mask:
    input:
        avi = "{datasets_output}raw_stack.avi",
        roi_data = "{datasets_output}roi_data.xlsx"
    output:
        cropped_avi = "{datasets_output}raw_stack_cropped.avi"
    params:
        crop_size = config["crop_size"],
        fps = config["fps"]
    run:
        from imutils.src import create_avi_from_mask

        create_avi_from_mask.main([
            '--video', str(input.avi),
            '--excel_file', str(input.roi_data),
            '--fps', str(params.fps),
            '--crop_size', str(params.crop_size),
        ])

rule downsample_for_DLC:
    input:
        avi = "{datasets_output}raw_stack_cropped.avi"
    params:
        fps = config["fps"]
    output:
        downsampled_avi = "{datasets_output}raw_stack_downsampled.avi"
    run:
        from imutils.src import downsample_script_512
        if config["downsample_for_DLC"] == 1:

            downsample_script_512.main([
                '--video', str(input.avi),
                '--output', str(output.downsampled_avi),
                '--fps', str(params.fps)
            ])

        else:
            touch("{output.downsampled_avi}")  # Create an empty file to continue with pipeline
            print("Empty downsampled_avi file created to continue pipeline.")




'''
rule downsample_for_DLC:
    input:
        script = "/scratch/neurobiology/zimmer/schaar/code/github/imutils/imutils/imutils/src/downsample_script_512.py",
        avi = "{datasets_output}raw_stack_cropped.avi"
    params:
        fps = config["fps"]
    output:
        downsampled_avi = "{datasets_output}raw_stack_downsampled.avi"
    run:
        if config["downsample_for_DLC"] == 1:
            shell("python {input.script} --video {input.avi} --output {output.downsampled_avi} --fps {params.fps} ")
        else:
            touch("{output.downsampled_avi}")  # Create an empty file to continue with pipeline
            print("Empty downsampled_avi file created to continue pipeline.")
'''

rule dlc_analyze_videos:
    input:
        script = "/scratch/neurobiology/zimmer/schaar/code/autoscope_ulises/packages/other/cluster_analyze_videos.py", #put this in environment package
        downsampled_avi = "{datasets_output}raw_stack_downsampled.avi",
        avi = "{datasets_output}raw_stack_cropped.avi"
    params:
        dlc_model_configfile_path = config["dlc_model_configfile_path"],
        network_string = config["network_string"],
        avi_used= "{datasets_output}raw_stack_downsampled.avi" if (config["downsample_for_DLC"] == 1) else "{datasets_output}raw_stack_cropped.avi"
    #TODO: run conda properly, instead of activating it in the shell. # conda: "/scratch/neurobiology/zimmer/.conda/envs/HR_tracker"
    output:
        #hdf5_file = "{datasets}raw_stack"+config["network_string"]+".h5"
        hdf5_file = "{datasets_output}raw_stack_downsampled"+config["network_string"]+".h5" if (config["downsample_for_DLC"] == 1) else "{datasets_output}raw_stack_cropped"+config["network_string"]+".h5"
    shell:
        """
        source /apps/conda/miniconda3/bin/activate /scratch/neurobiology/zimmer/.conda/envs/HR_tracker
        python {input.script} -path_config_file {params.dlc_model_configfile_path} -videofile_path {params.avi_used}
        """

# This rule erodes the binary mask from the background-subtracted image for a specified number of iterations and saves the eroded image.
rule erode_binary_mask:
    input:
        binary_img = "{datasets_output}raw_stack_background_subtracted_mask_cropped.btf",
    params:
        iter =  config['iterations']
    output:
        erode_img = "{datasets_output}raw_stack_background_subtracted_mask_eroded.btf"
    run:
        import pandas as pd
        import numpy as np
        import tifffile as tiff
        from scipy import ndimage

        with tiff.TiffFile(input.binary_img, multifile=False) as tif, tiff.TiffWriter(output.erode_img, bigtiff=True) as output_tif:
             for i, page in enumerate(tif.pages):
                 img = page.asarray()
                 eroded_img = ndimage.binary_erosion(img,iterations=params.iter)
                 eroded_img = eroded_img * 255
                 eroded_img = eroded_img.astype(np.uint8)
                 #eroded_img = np.array(eroded_img, dtype=np.uint8)
                 # save as a btf
                 output_tif.write(eroded_img,photometric='minisblack',contiguous=True)

rule create_centerline:
    input:
        #TODO: Try ancient() to see if I can avoid re-running when the script is modified
        input_binary_img = "{datasets_output}raw_stack_background_subtracted_mask_eroded.btf",
        hdf5_file = "{datasets_output}raw_stack_downsampled"+config["network_string"]+".h5" if (config["downsample_for_DLC"] == 1) else "{datasets_output}raw_stack_cropped"+config["network_string"]+".h5"
        #hdf5_file = "{datasets}raw_stack"+config["network_string"]+".h5" #"AVG_background_subtracted_normalisedDLC_resnet50_wbfm_nose_tailJan4shuffle1_1030000.h5"

    params:
        csv_output_path = "{datasets_output}",  # This cant go into inputs because it is not a file
        number_of_neighbours = "1",
        nose = config['nose'],
        tail = config['tail'],
        num_splines = config['num_splines'],
        downsample_for_DLC= config["downsample_for_DLC"],
        fill_with_DLC = config["fill_with_DLC"] #Improve so argparse takes boolean

    output :
        output_skel_X = "{datasets_output}skeleton_skeleton_X_coords.csv",
        output_skel_Y = "{datasets_output}skeleton_skeleton_Y_coords.csv",
        output_spline_K = "{datasets_output}skeleton_spline_K.csv",
        output_spline_X = "{datasets_output}skeleton_spline_X_coords.csv",
        output_spline_Y = "{datasets_output}skeleton_spline_Y_coords.csv",
        corrected_head = "{datasets_output}skeleton_corrected_head_coords.csv",
        corrected_tail = "{datasets_output}skeleton_corrected_tail_coords.csv"
    run:
        from centerline.dev import head_and_tail

        head_and_tail.main([
            '-i', str(input.input_binary_img),
            '-h5', str(input.hdf5_file),
            '-o', str(params.csv_output_path),
            '-nose', str(params.nose),
            '-tail', str(params.tail),
            '-num_splines', str(params.num_splines),
            '-n', str(params.number_of_neighbours),
            '-dlc', str(params.fill_with_DLC),
            '-ds', str(params.downsample_for_DLC),
        ])


rule reformat_skeleton_files:
    input:
        spline_K= "{datasets_output}skeleton_spline_K.csv",
        spline_X= "{datasets_output}skeleton_spline_X_coords.csv",
        spline_Y= "{datasets_output}skeleton_spline_Y_coords.csv"
    output:
        merged_spline_file = "{datasets_output}skeleton_merged_spline_data.csv",
    run:
        from centerline.dev import reformat_skeleton_files

        reformat_skeleton_files.main([
            '--input_spline_K', str(input.spline_K),
            '--input_spline_X', str(input.spline_X),
            '--input_spline_Y', str(input.spline_Y),
            '--o_path', str(output.merged_spline_file),
        ])

rule annotate_behaviour:
    input:
        curvature_file = "{datasets_output}skeleton_spline_K.csv"
    params:
        #pca_model_path = "/scratch/neurobiology/zimmer/ulises/code/curvature/curvature/models/1651_20220810_eigenworm_PCA_bodypart_30_to_80.pkl"
        pca_model_path = config["pca_model_path"],
        #features should be added here, and maybe rolling mean (or use averaged splineK instead)
        initial_segment = config["initial_segment"],
        final_segment = config["final_segment"],
        window = config["window"]
    output:
        principal_components = "{datasets_output}principal_components.csv",
        behaviour_annotation = "{datasets_output}beh_annotation.csv"

    run:
        from curvature.src import annotate_reversals_snakemake

        annotate_reversals_snakemake.main([
            '-i', str(input.curvature_file),
            '-pca', str(params.pca_model_path),
            '-i_s', str(params.initial_segment),
            '-f_s', str(params.final_segment),
            '-win', str(params.window),
            '-o_bh', str(output.behaviour_annotation),
            '-o_pc', str(output.principal_components),
        ])

rule make_beh_ann1:
    input:
        beh_annotation_file = "{datasets_output}beh_annotation.csv",
        input_file_path= "{datasets_output}"
    output:
        behaviour_annotation1 = "{datasets_output}beh_annotation1.csv"
    run:
        from curvature.src import make_beh_ann1

        make_beh_ann1.main([
            '--input_path', str(input.input_file_path),
            '--input_file', str(input.beh_annotation_file),
            '--output_file', str(output.behaviour_annotation1)
        ])

rule make_beh_ann2:
    input:
        beh_annotation_file = "{datasets_output}beh_annotation1.csv",
        input_file_path= "{datasets_output}"
    output:
        behaviour_annotation2 = "{datasets_output}beh_annotation2.csv"
    run:
        from curvature.src import make_beh_ann2

        make_beh_ann2.main([
            '--input_path', str(input.input_file_path),
            '--input_file', str(input.beh_annotation_file),
            '--output_file', str(output.behaviour_annotation2)

        ])

rule make_kymogram:
    input:
        curvature_file = "{datasets_output}skeleton_spline_K.csv",
        input_file_path= "{datasets_output}"
    output:
        kymogram = "{datasets_output}kymogram.png"
    run:
        from curvature.src import make_kymogram

        make_kymogram.main([
                    '--input_path', str(input.input_file_path),
                    '--spline_K', str(input.curvature_file),
                    '--output_file', str(output.kymogram)

        ])



rule make_ethogram:
    input:
        beh_annotation_file = "{datasets_output}beh_annotation1.csv",
        input_file_path= "{datasets_output}",
    output:
        ethogram = "{datasets_output}ethogram.png"
    run:
        from curvature.src import make_ethogram

        make_ethogram.main([
                    '--input_path', str(input.input_file_path),
                    '--beh_annotation', str(input.beh_annotation_file),
                    '--output_file', str(output.ethogram)

        ])



rule make_ethogram_led:
    input:
        beh_annotation_file = "{datasets_output}beh_annotation1.csv",
        input_file_path= "{datasets_output}"
    output:
        ethogram_led = "{datasets_output}ethogram_led.png"
    run:
        from curvature.src import make_ethogram_led

        make_ethogram_led.main([
                    '--input_path', str(input.input_file_path),
                    '--beh_annotation1', str(input.beh_annotation_file),
                    '--output_file', str(output.ethogram_led)

        ])

rule make_kymogram_smooth:
    input:
        curvature_file = "{datasets_output}skeleton_spline_K.csv",
        input_file_path= "{datasets_output}"
    output:
        kymogram_smooth = "{datasets_output}kymogram_smooth.png"
    run:
        from curvature.src import make_kymogram_smooth

        make_kymogram_smooth.main([
                    '--input_path', str(input.input_file_path),
                    '--spline_K', str(input.curvature_file),
                    '--output_file', str(output.kymogram_smooth)
       ])


rule rev_duration_all:
    input:
        beh_annotation1_file = "{datasets_output}beh_annotation1.csv",
        input_file_path= "{datasets_output}"
    params:
        fps = config["fps"]
    output:
        rev_duration = "{datasets_output}rev_duration_all.xlsx"

    run:
        from curvature.src import rev_duration

        rev_duration.main([
                    '--input_path', str(input.input_file_path),
                    '--beh_annotation1', str(input.beh_annotation1_file),
                    '--output_file', str(output.rev_duration),
                    '--fps', str(params.fps)
       ])


rule rev_reaction:
    input:
        beh_annotation1_file = "{datasets_output}beh_annotation1.csv",
        input_file_path= "{datasets_output}"
    output:
        rev_reaction = "{datasets_output}rev_reaction.xlsx"
    run:
        from curvature.src import rev_reaction

        rev_reaction.main([
                    '--input_path', str(input.input_file_path),
                    '--beh_annotation1', str(input.beh_annotation1_file),
                    '--output_file', str(output.rev_reaction),

       ])

